---
- name: setup nginx user
  become: true
  ansible.builtin.user:
    name: "nginx"
    state: present
    group: docker
    groups: root
    home: /home/nginx
    append: false

- name: create nginx directories
  file:
    state: directory
    path: "/home/{{ ansible_user }}/nginx"
    owner: nginx
    mode: 0644

- name: template nginx config
  template:
    src: files/nginx.conf.j2
    dest: "/home/{{ ansible_user }}/nginx/nginx.conf"
    mode: 0644
    owner: nginx

- name: copy certificate
  copy:
    src: "{{ nginx_certificate_src }}"
    dest: "{{ nginx_certificate_dest }}"
    decrypt: true
    mode: 0640
    owner: nginx

- name: copy key
  copy:
    src: "{{ nginx_key_src }}"
    dest: "{{ nginx_key_dest }}"
    decrypt: true
    mode: 0640
    owner: nginx

- name: run nginx container
  docker_container:
    name: nginx
    image: docker.io/nginx:alpine
    network_mode: host
    volumes:
      - "{{ nginx_certificate_dest }}:{{ nginx_certificate_dest }}"
      - "{{ nginx_key_dest }}:{{ nginx_key_dest }}"
      - "/home/{{ ansible_user }}/nginx/nginx.conf:/etc/nginx/nginx.conf"
