---
- name: create nginx directories
  file:
    state: directory
    path: "/home/{{ ansible_user }}/nginx"

- name: template nginx config
  template:
    src: files/nginx.conf.j2
    dest: "/home/{{ ansible_user }}/nginx/nginx.conf"
    mode: u=rw,g=r,o=r

- name: run nginx container
  docker_container:
    name: nginx
    image: docker.io/nginx:latest
    network_mode: host
    volumes:
      - "/home/{{ ansible_user }}/nginx/nginx.conf:/etc/nginx/nginx.conf"
