---
- hosts: debian
  become: yes
  roles:
    - k0s
    # - docker
    # - firewall
    # - cloudflared
    # - pihole
    # - heimdall
    # - prometheus.prometheus.node_exporter
    # - prometheus
    # - grafana
    # - traefik
