---
- hosts: debian
  become: yes
  roles:
    - docker
    - firewall
    - cloudflared
    - pihole
    - heimdall
    - prometheus.prometheus.node_exporter
    - prometheus
    - grafana
    - traefik
