---
- name: run heimdall container
  docker_container:
    state: started
    name: heimdall
    image: lscr.io/linuxserver/heimdall:latest
    networks:
      - name: media
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: America/Sao_Paulo
    volumes:
      - "{{ heimdall_path }}/config:/config"
    restart_policy: unless-stopped
