global:
  scrape_interval: "2m"

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node-exporter
    metrics_path: /metrics
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9100']


  
