global:
  scrape_interval: "2m"

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node-exporter
    metrics_path: /metrics
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9100']

  - job_name: grafana
    metrics_path: /metrics
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:3000']

  - job_name: traefik
    metrics_path: /metrics
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:8082']

  - job_name: cloudflared
    metrics_path: /metrics
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:8001']
